### ISSUE TITLE
Deploying EOES web application on AWS

### ISSUE THREAD

**Issue by roycol** [guashtiSingh/EatOutEatSafeSoftwareProject#3]
As we have IIS installed on AWS, now it's time to deploy the EOES to IIS. 
In order for that, followings are required.
1. Install either web deploy and visual studio on the server.
2. Make sure IIS settings and framework version to run .net application

**Comment by iloy1004** [comment]
@roycol @AnjithBabu I've tried to deploy our web site on virtual server, but I'm getting some error message now.  I guess it's because some problem in Web.config file... Please check out on our server

**Comment by chemceem** [comment]
Is it possible to deploy to the server directly from Visual Studio ?
Were you able to successfully install and configure mysql in the server ?

**Comment by iloy1004** [comment]
@chemceem Yes, it's possible to deploy via Visual studio directly. So I've done to deploy by using VS, but this web site is occuring error, 404.3? 405? anyways.. the error message said "if the page is a script, add a handler.. " that's why I thought it might be because of setting problem. 
My sql was installed succesfully without any error, and database and tables were set up too.  So.. I think My sql is fine..

**Comment by roycol** [comment]
I'm checking IIS setting. As far as I investigated, a mime type(aspx//application/aspx) missed to register on IIS. I've added it, but still, IIS doesn't recognize .aspx extension.

**Comment by roycol** [comment]
I'm trying to deploy again. (looks what Jihee has done and set up for deployment are fine though.)
For any case that we might miss a tiny step and it causes the problem, I'll thoroughly check and follow the instruction of Microsoft(https://www.asp.net/mvc/overview/deployment/visual-studio-web-deployment/deploying-to-iis).

**Comment by roycol** [comment]
I've solved the issue. Main cause of this issue was .Net framework. We didn't completely install it before setting IIS.
